"use client";
import { ClipboardList, ArrowRight, ArrowDownToLine } from "lucide-react";
import {
  resolutionPlan,
  resolutionPacket,
  type ResolutionStep,
} from "@/lib/resolution";
import type { CaseResult } from "@/lib/types";

export function ResolutionDesk({
  result,
  onNavigate,
}: {
  result: CaseResult;
  onNavigate: (target: ResolutionStep["target"]) => void;
}) {
  const plan = resolutionPlan(result);
  function download() {
    const url = URL.createObjectURL(
      new Blob([resolutionPacket(result)], {
        type: "text/plain;charset=utf-8",
      }),
    );
    const link = document.createElement("a");
    link.href = url;
    link.download = `${result.email.email_id}-r${result.version}-evidence-handoff.txt`;
    link.click();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  return (
    <section className="resolution-desk">
      <div className="resolution-heading">
        <ClipboardList size={22} />
        <div>
          <h3>From finding to next action</h3>
          <p>
            {plan.label} · revision {result.version}
          </p>
        </div>
      </div>
      <p className="resolution-note">
        This source-based checklist is deterministic, not generated by an LLM.
        It helps your team resolve the case; it never authorises cargo release.
      </p>
      <ol>
        {plan.steps.map((step, index) => (
          <li key={`${index}-${step.title}`}>
            <h4>{step.title}</h4>
            <p>{step.detail}</p>
            <button
              className="text-button"
              onClick={() => onNavigate(step.target)}
            >
              Inspect {step.target === "history" ? "audit trail" : step.target}{" "}
              <ArrowRight size={14} />
            </button>
          </li>
        ))}
      </ol>
      <button className="button secondary" onClick={download}>
        <ArrowDownToLine size={16} /> Download evidence handoff
      </button>
      <p className="resolution-note">
        Includes next actions, all seven field results, source fingerprints and
        revision references. Review before sharing; nothing is sent
        automatically.
      </p>
    </section>
  );
}
