import type { Category } from "../lib/types";

// Independently authored task descriptions. No organiser email, key, ID or
// generated-corpus row is loaded here. These are training examples, not tests.
// Subjects/bodies below are deliberately varied and include contrasting intent.
export const ROUTER_TRAINING_PROVENANCE =
  "Independently authored English shipping-desk examples, 2026-09-21; synthetic training data, not historical customer messages.";
export const ROUTER_TRAINING: Record<
  Category,
  { subjects: string[]; bodies: string[] }
> = {
  BL_COMPARISON: {
    subjects: [
      "Draft BL check",
      "Verify shipment documents",
      "Please compare the SI and bill of lading",
      "TO CONFIRM DOCS",
      "Request BL draft",
      "Document discrepancy review",
      "Amend draft bill",
      "Shipping paperwork confirmation",
      "AIE document checking",
      "Are the draft details correct?",
    ],
    bodies: [
      "Please compare the attached shipping instruction with the draft bill of lading. Report every field that differs before final release.",
      "Can you check this draft BL against our SI and confirm whether the consignee, ports and quantities agree?",
      "The carrier sent a draft bill. Please verify the shipping details against the instructions and highlight discrepancies.",
      "Inspect both shipment documents and tell us whether the draft matches the authorized shipping instruction.",
      "We need a side-by-side comparison of the SI and B/L. Do not issue the final bill until the discrepancies have been resolved.",
      "Kindly review the attached draft and instructions. We are asking for validation, not preparation of a new instruction.",
      "Please send the draft BL so that the documentation desk can check it against the instruction. We are still waiting for the draft.",
      "The draft bill of lading has not arrived. Please arrange a copy for checking against the SI.",
      "Could you forward the proposed BL for verification? Our shipping instruction is already submitted.",
      "An amended draft BL is attached. Check the revised port of discharge against the SI before confirming.",
      "Please compare SI and draft BL even though the SI has an incomplete field. Escalate anything you cannot determine.",
      "The scanned bill needs to be checked against the shipping instruction. Flag unreadable values rather than guessing.",
      "Please confirm whether the attached draft documents are in order. Compare the bill of lading with our instruction.",
      "We found a possible change in the consignee. Please verify the BL draft against the SI and advise.",
      "The carrier requires draft confirmation. Please check the two attached shipping documents for any mismatched field.",
      "Please review the B/L and S/I together. We need all differences listed before the carrier issues the original.",
      "Kindly validate the shipper, consignee, notify party, load port, discharge port, container count and weight between SI and draft BL.",
      "Check the draft against the shipping instructions already supplied. Send a discrepancy report rather than creating another SI.",
      "The paperwork is for document verification. We have an SI and a draft bill; please identify inconsistencies.",
      "Can the BL checking team review the carrier draft? The booking instruction is the source of truth.",
      "The instruction request is finished. The current task is to compare the draft bill against that instruction.",
      "Our previous billing issue is resolved. Please now verify the attached draft BL against the shipping instruction.",
      "Although this thread originally concerned preparing an SI, that work is complete. Please inspect the draft BL for differences.",
      "Please compare the shipping instruction and the carrier document. The second attachment may be an invoice instead of the required BL.",
      "The draft is missing from the attachments. We still need the SI-versus-BL verification once a readable draft is provided.",
      "Please check the carrier's bill draft against the customer instructions and confirm the exact shipment fields.",
      "We need to know whether this draft is consistent with the SI. Refer uncertain fields for review.",
      "Kindly send the draft bill for checking. We cannot verify the shipment before receiving it.",
      "Both shipping documents are enclosed for comparison and confirmation. Please check every required field.",
      "Review the amended BL document alongside the instruction. Determine whether the requested corrections have been made.",
    ],
  },
  SI_REQUEST: {
    subjects: [
      "Prepare shipping instruction",
      "REQUEST SI",
      "Customer SI needed",
      "SI - DIRECT carrier submission",
      "CUST SI for booking",
      "Shipping instructions to be lodged",
      "New shipment instruction",
      "Please issue SI",
      "SI submission before cutoff",
      "Provide carrier instructions",
    ],
    bodies: [
      "Please prepare the shipping instruction for the new booking using the shipment details below. Submit it to the carrier before cutoff.",
      "We need a customer SI created from the order confirmation. Please draft the instruction and return it for submission.",
      "Kindly lodge our shipping instructions with the line. The draft bill will be requested after the instruction is accepted.",
      "Please find shipping instruction details for the booking below. Submit these to the carrier and revert with a draft BL once available.",
      "The shipment details are ready. Please issue the SI and arrange submission to the carrier.",
      "Can the shipping instruction team prepare an SI for this new cargo booking? No draft bill exists yet.",
      "Please send our customer instructions to the line. Once submitted, ask the carrier for a BL draft.",
      "We require SI preparation, not comparison. The carrier has not produced a draft bill of lading yet.",
      "Create the shipping instruction from these details: shipper ALPHA EXPORT, consignee BETA IMPORT, notify party BETA IMPORT, loading port SINGAPORE and discharge port ROTTERDAM.",
      "The customer has provided the following shipping instructions. Please arrange the carrier submission and return a draft BL later.",
      "Shipping instruction for the order is below. Shipper: ALPHA EXPORT LTD. Consignee: BETA TRADING LTD. Notify party: BETA TRADING LTD. Gross weight: 42000 KG. Please revert with draft BL once available.",
      "Please prepare CUST SI using the shipment particulars. Required documents include original invoice, packing list and original BL; these are delivery requirements, not documents for comparison.",
      "Submit the SI before today's cutoff. Details of the shipper, consignee and ports follow. Obtain the draft bill afterward.",
      "The instructions need to be created for a fresh booking. Please send the completed SI to the shipping line.",
      "Customer shipping information is enclosed for SI preparation and submission. We will check the BL when the carrier provides one.",
      "Please arrange a new shipping instruction. Use the order details below and advise when the instruction has been lodged.",
      "Kindly prepare the SI with the shipper and notify-party addresses below. The carrier draft will follow after submission.",
      "Please find our Shipping Instruction below for your processing. POL: SINGAPORE. POD: ROTTERDAM. Please revert with a draft BL once it is available.",
      "We have not submitted the shipping instructions. Please complete that task before requesting the BL draft.",
      "Please enter these cargo details into the carrier instruction. This is the initial SI request for a new shipment.",
      "The customer asks us to provide the shipping instruction, including bill type and original document requirements.",
      "Kindly create the carrier SI. Shipper and consignee particulars are listed in the email body; please use those details.",
      "Our previous draft review is closed. This message is for preparing a new shipping instruction for a different booking.",
      "The earlier invoice query is resolved. Please now prepare the shipping instructions from the order details.",
      "Please submit the updated customer SI to the carrier. Request a draft bill after the carrier has received the instructions.",
      "We need the SI team to arrange shipment instructions directly with the line using these cargo particulars.",
      "The order is confirmed; prepare shipping instructions for carrier submission. No comparison is required at this stage.",
      "Please provide the initial SI containing the company addresses, ports, container quantity and gross weight.",
      "This is a request to lodge the customer's shipping instructions. Return the BL draft when it becomes available later.",
      "Please prepare and submit our SI with the full shipment data below. Documents required after shipping: invoice, packing list and bill of lading.",
    ],
  },
  INVOICE_QUERY: {
    subjects: [
      "Invoice clarification",
      "Missing GR for billing",
      "Cancel duplicate invoice",
      "Local charge breakdown",
      "Freight charges query",
      "D and D invoice",
      "Payment discrepancy",
      "Billing question",
      "Credit note required",
      "Revise invoice amount",
    ],
    bodies: [
      "Please explain the charges on this invoice and send a breakdown of the freight and local fees.",
      "The goods receipt is missing, so the invoice cannot be processed for payment. Please arrange the GR.",
      "We need to cancel a duplicate invoice and issue a credit note. Please confirm the billing adjustment.",
      "The freight amount does not match the agreed rate. Please revise the invoice and advise the correct total.",
      "Does this invoice include terminal handling charges, or will they be billed separately?",
      "Please clarify the detention and demurrage charges for this shipment before we approve payment.",
      "The customer disputes the local charges. Please provide an itemized billing explanation.",
      "An invoice was raised against the wrong order. Please cancel it and reverse the posting.",
      "Please send the missing invoice so that we can complete the payment process.",
      "We cannot pay the freight invoice until the goods receipt has been recorded. Kindly resolve the missing GR.",
      "The invoiced total is incorrect. Please review the agreed charges and issue the corrected bill.",
      "Could you explain why the customer received two invoices for the same handling fee?",
      "Please arrange a credit note for the overcharged amount and confirm the revised balance.",
      "The D&D invoice needs clarification. We believe some detention days were included twice.",
      "Please advise whether the local charge includes telex release or if another invoice is expected.",
      "Our invoice payment is blocked by missing GR. The shipping paperwork is not the issue in this request.",
      "Please check the customs duty invoice and explain the tax amount before we pay the recorded supplier.",
      "We paid the customs invoice yesterday. Please clarify why the charge remains outstanding.",
      "Can you confirm the agreed invoice discount and send a revised calculation? This is a billing query.",
      "The invoice is for a cancelled booking. Please issue a cancellation and reverse the goods posting.",
      "The previous BL check has finished. Please now explain the invoice charges in this thread.",
      "Although the subject mentions shipping instructions, our current question concerns the invoice amount.",
      "Kindly clarify the terminal handling fee shown on the supplier's invoice. We need the charge breakdown.",
      "Please send the freight invoice and payment reference for this completed shipment.",
      "There is a duplicate local service fee on our invoice. Please remove it and resend the billing document.",
      "The finance desk needs an explanation for the increased freight total before releasing payment.",
      "Please revise this billing record; the invoiced currency and agreed payment amount do not match.",
      "We are querying the invoice, not comparing shipping documents. Kindly explain the additional charge.",
      "Please clarify why demurrage was invoiced when the container was collected before the free period ended.",
      "We need the billing team to correct the supplier invoice and confirm the credit note amount.",
    ],
  },
  GENERAL: {
    subjects: [
      "Operations update",
      "Daily berthing report",
      "Weekly shipment summary",
      "Office closure notice",
      "SLA reminder for outstanding shipments",
      "RPA billing process completed",
      "Outstanding BL list",
      "Pending BL release status",
      "Team announcement",
      "Reminder - submit SI and AED for all pending shipments",
      "Security incident report",
      "Suspicious email reported to IT",
      "Phishing awareness update",
    ],
    bodies: [
      "Please find the weekly shipment status summary for reference. Loading is complete and documents will follow.",
      "The daily berthing report is available. The vessel arrived on schedule; this is an operational status update.",
      "Our office will be closed for the public holiday and will reopen the next working day.",
      "This is an automated notification: the billing process completed successfully. No action is required.",
      "Please find the list of outstanding BL releases for the documentation team. This is the daily status report.",
      "Reminder to all teams: submit SI and AED for pending shipments before the daily cutoff. Refer to the outstanding list.",
      "Wishing all colleagues a happy new year. Normal office operations resume after the holiday.",
      "The shipping schedule has changed. Please take note of the revised vessel arrival time.",
      "The RPA bot finished the goods-receipt and billing task successfully. This message is informational.",
      "Please review the team meeting agenda for the upcoming operations call. No shipment document verification is requested.",
      "A summary of pending BL releases is attached for workload planning. Please note the outstanding items.",
      "The daily service-level reminder covers all pending shipping instructions. Please refer to the SLA dashboard.",
      "The invoice process has completed automatically. This is a system completion notice rather than a billing dispute.",
      "The vessel has berthed and discharge will start tomorrow. This email provides an operational update.",
      "Please find the monthly performance report and documentation backlog summary for your information.",
      "There will be scheduled system maintenance tonight. The documentation portal will be temporarily unavailable.",
      "This is a human-resources notice about the upcoming office holiday and staff availability.",
      "Please see the delivery planning update. No change to shipment documents has been requested.",
      "Our weekly review of outstanding invoices and BL releases is ready for the operations meeting.",
      "The automation job finished processing today's invoices. No action required; the run completed normally.",
      "Please take note of the list of outstanding bills of lading. It is a status summary, not a request to compare drafts.",
      "The office resumes normal operations on Monday. Please share this holiday announcement with your team.",
      "This reminder concerns submission deadlines across the entire shipping desk, not preparation of one customer's instruction.",
      "The earlier BL discrepancy is resolved. This email only reports that the shipment has departed.",
      "Please find today's berth allocation report and vessel movement summary. For your reference only.",
      "The time-off request has been submitted to the manager. This is an administrative notification.",
      "An operations meeting has been moved to Friday. Please update your calendar accordingly.",
      "The process completed message confirms that the invoice automation ran successfully; no finance question remains.",
      "Attached is the outstanding documentation list for all shipments. Kindly take note of the team's workload.",
      "A public holiday reminder for all employees: the office is closed and normal service returns the following day.",
      "I am reporting a suspected phishing email to our IT security team. It claims my mailbox is full. Please investigate the suspicious message; I have not clicked the link.",
      "For the incident register: an external sender asked for my email password. I reported the message as phishing and need the security desk to investigate.",
      "Security awareness notice for colleagues: never enter your credentials after receiving a mailbox suspension warning. Report suspicious messages to our IT team.",
      "An employee reported a fake parcel fee email. This internal incident report asks IT to investigate the suspicious payment link, not to pay it.",
      "Please investigate this security incident. A suspicious message promised an unexpected prize and asked for bank details. I am forwarding a report to the security team.",
      "Our weekly cybersecurity briefing includes reports of phishing attempts and fraudulent account-verification messages. This is an internal awareness update.",
    ],
  },
  SPAM: {
    subjects: [
      "Claim your unexpected prize",
      "Urgent mailbox verification",
      "Guaranteed investment returns",
      "Parcel fee required immediately",
      "Exclusive marketing offer",
      "You have been selected",
      "Invoice payment - verify account",
      "Account suspension warning",
      "Amazing discount expires today",
      "Unexpected reward waiting",
    ],
    bodies: [
      "Congratulations, your address won a cash prize. Click this link now and provide bank details to claim the reward.",
      "Your mailbox is full and will be disabled. Enter your password at the verification page immediately.",
      "Invest in our scheme for guaranteed extraordinary returns. Send money now to secure the exclusive opportunity.",
      "Your unexpected parcel is being held for a small fee. Pay through this unfamiliar link within a few hours to release it.",
      "You have been selected for a free gift card. Complete a survey and pay a delivery charge to claim the prize.",
      "I am a foreign bank officer seeking help to transfer a large inheritance. Reply with your bank account details.",
      "Limited time offer on our marketing software. Buy now before this exclusive discount expires.",
      "Your email account will be suspended unless you verify your credentials at the linked website now.",
      "You won a new phone in a draw you never entered. Pay a small shipping fee and share your personal details.",
      "An unsolicited investment promises guaranteed profits with no risk. Transfer funds today to receive the bonus.",
      "Your package cannot be delivered because a customs fee remains unpaid. Confirm payment at this link or it will be returned.",
      "This confidential banking proposal will release millions to you. Send identification and account information to proceed.",
      "Claim your lottery winnings now. Our agent needs a processing payment before releasing your prize.",
      "Unsolicited promotional mail: subscribe now to receive an enormous discount on logistics software.",
      "Your mailbox has undelivered messages. Confirm your password through this account-verification link.",
      "A stranger offers a business partnership involving millions and asks for bank details to receive the transfer.",
      "Act now to double your investment with guaranteed returns. This special money-making offer expires today.",
      "Dear user, update your account credentials to prevent suspension. Use the verification page linked below.",
      "An unexpected courier message demands an immediate online fee and threatens to return the parcel.",
      "You have been chosen as a lucky winner. Claim a shopping voucher after paying a small release charge.",
      "Our unsolicited sales promotion offers a huge software discount. Buy now before the deal disappears.",
      "This email pretends to concern invoice payment but asks you to claim an unrelated prize and reveal bank details.",
      "Your storage limit is exceeded. Visit the linked login page and enter your email password to keep the account active.",
      "You are invited to an unknown cryptocurrency scheme with guaranteed high returns and an urgent payment deadline.",
      "A supposed bank employee wants to share an inheritance if you first provide personal and financial information.",
      "Get rich quickly with our exclusive investment. Send the initial fee now and claim guaranteed profits tomorrow.",
      "This is an unsolicited advertisement encouraging you to buy a product immediately with a large promotional discount.",
      "Congratulations on winning an expensive device. Complete the attached survey and pay a small postage fee to receive it.",
      "Your parcel is on hold. Follow the unfamiliar payment link within twenty-four hours or the package will be returned.",
      "An unknown sender promises a reward and asks you to confirm account credentials to claim it.",
    ],
  },
};

export function authoredRoutingRows() {
  const rows: {
    category: Category;
    subject: string;
    body: string;
    split: "train" | "validation";
  }[] = [];
  const detail =
    "\n\nShipment particulars:\nShipper: ALPHA PAPER EXPORT LTD\nConsignee: BETA DISTRIBUTION LTD\nNotify party: BETA DISTRIBUTION LTD\nPort of loading: SINGAPORE\nPort of discharge: ROTTERDAM\nContainer count: 2\nGross weight: 42000 KG";
  for (const [category, examples] of Object.entries(ROUTER_TRAINING) as [
    Category,
    (typeof ROUTER_TRAINING)[Category],
  ][]) {
    for (const [index, body] of examples.bodies.entries()) {
      const split = index % 6 === 5 ? "validation" : "train";
      for (const offset of [0, 3, 6]) {
        const subject =
          examples.subjects[(index + offset) % examples.subjects.length];
        rows.push({ category, subject, body, split });
        rows.push({
          category,
          subject,
          body: `Dear operations team,\n\n${body}${detail}\n\nBest Regards,\nExample coordinator`,
          split,
        });
      }
      // Blank/generic subjects prevent a classifier from learning only subject conventions.
      rows.push({
        category,
        subject: index % 2 ? "Shipment follow-up" : "",
        body,
        split,
      });
    }
  }
  return rows;
}
